name: 'Chromatic Publish on PR'

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  chromatic:
    name: 'Chromatic Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          # Grab this from the Chromatic manage page
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Set URL
        if: success()
        run: echo "CHROMATIC_URL=${{ steps.chromatic.outputs.storybookUrl }}" >> $GITHUB_ENV

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Storybook Preview
            [View Storybook](${{ env.STORYBOOK_URL }})
